### ISSUE TITLE
Errors and warnings are unreadable

### ISSUE THREAD

**Issue by WeetHet** [ssaunderss/zed-tokyo-night#1]
I don't know exactly how themes in zed work, could you please fix the error and warning background/foreground colours, so they would be readable
<img width="641" alt="Screenshot 2024-02-15 at 10 31 29" src="https://github.com/ssaunderss/zed-tokyo-night/assets/43210583/385a35dc-b3b2-4fe8-9638-bf7f87af896a">
<img width="681" alt="Screenshot 2024-02-15 at 10 31 21" src="https://github.com/ssaunderss/zed-tokyo-night/assets/43210583/6b6cf7a7-5967-45c2-b80c-932e3baf10c2">

**Comment by ssaunderss** [comment]
I think I know what's causing this, I'll look into this shortly

**Comment by ssaunderss** [comment]
Hi @WeetHet, just finished porting all of the themes and this should be one of the many fixes. `v0.0.2` was just merged into the zed extension repo, you might have to reinstall for the changes to take effect. If anything else looks off with the new changes that went out feel free to create another issue. Thanks!
