### ISSUE TITLE
Markdown syntax issues

### ISSUE THREAD

**Issue by Dannyholt** [ssaunderss/zed-tokyo-night#2]
Can you improve the highlighting for the markdown syntax. Below is an example of Tokyo Night and another for the One Dark theme.

## Tokyo Night

![CleanShot 2024-02-21 at 15 58 35@2x](https://github.com/ssaunderss/zed-tokyo-night/assets/1708426/e1188b8d-26e4-4276-a4be-d492d7813bdf)

## One Dark

![CleanShot 2024-02-21 at 16 00 14@2x](https://github.com/ssaunderss/zed-tokyo-night/assets/1708426/3f129afc-d2ca-4e3c-a87c-da98c6bf932c)

**Comment by ssaunderss** [comment]
Resolved by https://github.com/ssaunderss/zed-tokyo-night/pull/6
